/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_device_information             14
#define gattdb_manufacturer_name_string       16
#define gattdb_model_number_string            18
#define gattdb_hardware_revision_string       20
#define gattdb_firmware_revision_string       22
#define gattdb_system_id                      24
#define gattdb_health_thermometer             25
#define gattdb_temperature_measurement        27
#define gattdb_temperature_type               30
#define gattdb_intermediate_temperature       32
#define gattdb_measurement_interval           35
#define gattdb_valid_range                    37
#define gattdb_ota                            38
#define gattdb_ota_control                    40

#define gattdb_generic_attribute_len          2
#define gattdb_service_changed_char_len       4
#define gattdb_database_hash_len              16
#define gattdb_client_support_features_len    1
#define gattdb_device_name_len                19
#define gattdb_device_information_len         2
#define gattdb_manufacturer_name_string_len   12
#define gattdb_model_number_string_len        10
#define gattdb_hardware_revision_string_len   5
#define gattdb_firmware_revision_string_len   8
#define gattdb_system_id_len                  8
#define gattdb_health_thermometer_len         2
#define gattdb_temperature_measurement_len    17
#define gattdb_temperature_type_len           1
#define gattdb_intermediate_temperature_len   17
#define gattdb_measurement_interval_len       2
#define gattdb_valid_range_len                4
#define gattdb_ota_len                        16


#endif // __GATT_DB_H
